logging:
  level: INFO
  loggers:
    com.asverma: DEBUG

server:
  type: default
  maxThreads: 50
  minThreads: 8
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001
  requestLog:
    appenders: []

database:
  driverClass: org.postgresql.Driver
  user: root
  password: rootpass
  url: jdbc:postgresql://school-api-2.c8s85mwv7khu.eu-west-1.rds.amazonaws.com:5432/postgres
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

swagger:
  resourcePackage: com.asverma.resources
