version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpass
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  schoolapi:
    build: .
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - postgres

volumes:
  postgres:

